<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RouterNodesSeeder extends Seeder {
  public function run(): void {
    DB::table('router_nodes')->insert([
      // Airports
      [
        'id' => '@AIR_EBBR',
        'description' => 'Brussels Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 50.90138,
        'lonDeg' => 4.48444,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EBAW',
        'description' => 'Antwerp International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 51.18944,
        'lonDeg' => 4.46027,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_KLAX',
        'description' => 'Los Angeles International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 33.94277,
        'lonDeg' => -118.4080,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 11,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EBCI',
        'description' => 'Brussels South Charleroi Airport',
        'location_type' => 'AIRPORT',
        'lonDeg' => 4.45388,
        'latDeg' => 50.45916,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 14,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EDDM',
        'description' => 'Munich International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 48.35388,
        'lonDeg' => 11.78611,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 12,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EGKK',
        'description' => 'London Gatwick Airport',
        'location_type' => 'AIRPORT',
        'lonDeg' => -0.19027,
        'latDeg' => 51.14805,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 5,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EPWA',
        'description' => 'Warsaw Chopin Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 52.16583,
        'lonDeg' => 20.96722,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 13,
        'created_at' => now(),
        'updated_at' => now(),
      ],


      // DISTRIBUTION_CENTERs
      [
        'id' => '@DC_BRUSSELS',
        'description' => 'EU Distribution Hub Brussels',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.9013,
        'lonDeg' => 4.48444,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_ANTWERP',
        'description' => 'Distribution Center Antwerp',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.18944,
        'lonDeg' => 4.46027,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_LOS_ANGELES',
        'description' => 'NA Distribution Hub Los Angeles',
        'location_type' => 'DISTRIBUTION_CENTER',
        'lonDeg' => -118.40805,
        'latDeg' => 33.94277,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 11,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_CHARLEROI',
        'description' => 'Charleroi Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.45916,
        'lonDeg' => 4.45388,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 14,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_MUNICH',
        'description' => 'Munich Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'lonDeg' => 11.78611,
        'latDeg' => 48.35388,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 12,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_LONDON',
        'description' => 'London Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.1480,
        'lonDeg' => -0.19027,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 5,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_WARSAW',
        'description' => 'Warsaw Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'lonDeg' => 20.96722,
        'latDeg' => 52.16583,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 13,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_TILBURG',
        'description' => 'Tilburg Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.565,
        'lonDeg' => 5.09111,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 15,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_BASTOGNE',
        'description' => 'Bastogne Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.00361,
        'lonDeg' => 5.72083,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 16,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_GHENT',
        'description' => 'Ghent Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.05,
        'lonDeg' => 3.71666,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 17,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_LILLE',
        'description' => 'Lille Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.63333,
        'lonDeg' => 3.06666,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 18,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_PARIS',
        'description' => 'Paris Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 48.85666,
        'lonDeg' => 2.35222,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 10,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      //pickup_points
      [
        'id' => '@PIP_0001',
        'description' => 'Pick-up Point Antwerp 1',
        'location_type' => 'PICKUP_POINT',
        'latDeg' => 51.18944,
        'lonDeg' => 4.46027,
        'isEntry' => false,
        'isExit' => true,
        'city_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      //TEST_NODE
      // [
      //   'id' => '@DISCONNECTED_TEST_NODE',
      //   'description' => 'Disconnected test node',
      //   'location_type' => 'DISTRIBUTION_CENTER',
      //   'latDeg' => 54.1536,
      //   'lonDeg' => 16.9913,
      //   'isEntry' => false,
      //   'isExit' => true,
      //   'city_id' => 1,
      //   'created_at' => now(),
      //   'updated_at' => now(),
      // ],
    ]);
  }
}

?>