<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RouterEdgesSeeder extends Seeder {
  public function run(): void {
    DB::table('router_edges')->insert([
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@DC_BRUSSELS',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBAW',
        'destination_node' => '@DC_ANTWERP',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_ANTWERP',
        'destination_node' => '@DC_BRUSSELS',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_ANTWERP',
        'destination_node' => '@PIP_0001',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_KLAX',
        'destination_node' => '@AIR_EBAW',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_KLAX',
        'destination_node' => '@DC_LOS_ANGELES',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_ANTWERP',
        'destination_node' => '@DC_TILBURG',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_BRUSSELS',
        'destination_node' => '@DC_TILBURG',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_GHENT',
        'destination_node' => '@DC_ANTWERP',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_GHENT',
        'destination_node' => '@DC_BRUSSELS',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_GHENT',
        'destination_node' => '@DC_CHARLEROI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_GHENT',
        'destination_node' => '@DC_LILLE',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_PARIS',
        'destination_node' => '@DC_LILLE',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@AIR_EPWA',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_WARSAW',
        'destination_node' => '@AIR_EPWA',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@AIR_EDDM',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_MUNICH',
        'destination_node' => '@AIR_EDDM',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_CHARLEROI',
        'destination_node' => '@DC_BRUSSELS',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_CHARLEROI',
        'destination_node' => '@AIR_EBCI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_CHARLEROI',
        'destination_node' => '@DC_BASTOGNE',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_BRUSSELS',
        'destination_node' => '@DC_BASTOGNE',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EGKK',
        'destination_node' => '@AIR_EBCI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EGKK',
        'destination_node' => '@DC_LONDON',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EGKK',
        'destination_node' => '@AIR_EHAM',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EHAM',
        'destination_node' => '@DC_AMSTERDAM',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EGKK',
        'destination_node' => '@AIR_EHEH',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EHEH',
        'destination_node' => '@DC_EINDHOVEN',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@AIR_LEMD',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LEMD',
        'destination_node' => '@DC_MADRID',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LEMD',
        'destination_node' => '@AIR_LEBL',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LEBL',
        'destination_node' => '@DC_BARCELONA',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LEMD',
        'destination_node' => '@AIR_LEMG',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LEMG',
        'destination_node' => '@DC_MALAGA',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@AIR_EDDL',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EDDT',
        'destination_node' => '@AIR_EDDL',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_DUSSELDORF',
        'destination_node' => '@AIR_EDDL',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EDDT',
        'destination_node' => '@DC_BERLIN',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EPWA',
        'destination_node' => '@AIR_EPKT',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EPWA',
        'destination_node' => '@AIR_EPPO',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_KATOWICE',
        'destination_node' => '@AIR_EPKT',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_PONZAN',
        'destination_node' => '@AIR_EPPO',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LPPT',
        'destination_node' => '@AIR_EBCI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LPPT',
        'destination_node' => '@AIR_LPPR',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LPPT',
        'destination_node' => '@DC_LISBOA',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_PORTO',
        'destination_node' => '@AIR_LPPR',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@AIR_LIML',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LIRF',
        'destination_node' => '@AIR_LIML',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_MILAN',
        'destination_node' => '@AIR_LIML',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_ROME',
        'destination_node' => '@AIR_LIRF',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@AIR_LGAV',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_LGAV',
        'destination_node' => '@AIR_LGIR',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_ATHENS',
        'destination_node' => '@AIR_LGAV',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_HERAKLION',
        'destination_node' => '@AIR_LGIR',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EGKK',
        'destination_node' => '@AIR_EGCC',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_MANCHESTER',
        'destination_node' => '@AIR_EGCC',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EKCH',
        'destination_node' => '@AIR_EBBR',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EKCH',
        'destination_node' => '@AIR_EKBI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EKCH',
        'destination_node' => '@AIR_EKYT',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EKCH',
        'destination_node' => '@DC_COPENHAGEN',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EKYT',
        'destination_node' => '@DC_AALBORG',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EKBI',
        'destination_node' => '@DC_BILLUND',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_ENGM',
        'destination_node' => '@AIR_EBBR',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_ENGM',
        'destination_node' => '@DC_OSLO',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_ESSB',
        'destination_node' => '@AIR_EBBR',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_ESSB',
        'destination_node' => '@DC_STOCKHOLM',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EFHK',
        'destination_node' => '@AIR_EBBR',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EFHK',
        'destination_node' => '@DC_HELSINKI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
    ]);
  }
}