<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RouterEdgesSeeder extends Seeder {
  public function run(): void {
    DB::table('router_edges')->insert([
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@DC_BRUSSELS',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBAW',
        'destination_node' => '@DC_ANTWERP',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_ANTWERP',
        'destination_node' => '@DC_BRUSSELS',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_ANTWERP',
        'destination_node' => '@PIP_0001',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_KLAX',
        'destination_node' => '@AIR_EBAW',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_KLAX',
        'destination_node' => '@DC_LOS_ANGELES',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_ANTWERP',
        'destination_node' => '@DC_TILBURG',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_BRUSSELS',
        'destination_node' => '@DC_TILBURG',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_GHENT',
        'destination_node' => '@DC_ANTWERP',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_GHENT',
        'destination_node' => '@DC_BRUSSELS',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_GHENT',
        'destination_node' => '@DC_CHARLEROI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_GHENT',
        'destination_node' => '@DC_LILLE',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_PARIS',
        'destination_node' => '@DC_LILLE',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@AIR_EPWA',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_WARSAW',
        'destination_node' => '@AIR_EPWA',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EBBR',
        'destination_node' => '@AIR_EDDM',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_MUNICH',
        'destination_node' => '@AIR_EDDM',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_CHARLEROI',
        'destination_node' => '@DC_BRUSSELS',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_CHARLEROI',
        'destination_node' => '@AIR_EBCI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_CHARLEROI',
        'destination_node' => '@DC_BASTOGNE',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@DC_BRUSSELS',
        'destination_node' => '@DC_BASTOGNE',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EGKK',
        'destination_node' => '@AIR_EBCI',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'origin_node' => '@AIR_EGKK',
        'destination_node' => '@DC_LONDON',
        'weight' => 1.0,
        'isUniDirectional' => false,
        'validFrom' => now(),
        'validTo' => now()->addYears(10),
        'created_at' => now(),
        'updated_at' => now(),
      ],
    ]);
  }
}