<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RouterNodesSeeder extends Seeder {
  public function run(): void {
    DB::table('router_nodes')->insert([
      // Airports
      [
        'id' => '@AIR_EBBR',
        'description' => 'Brussels Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 50.90138,
        'lonDeg' => 4.48444,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EBAW',
        'description' => 'Antwerp International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 51.18944,
        'lonDeg' => 4.46027,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_KLAX',
        'description' => 'Los Angeles International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 33.94277,
        'lonDeg' => -118.4080,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 11,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EBCI',
        'description' => 'Brussels South Charleroi Airport',
        'location_type' => 'AIRPORT',
        'lonDeg' => 4.45388,
        'latDeg' => 50.45916,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 14,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EDDM',
        'description' => 'Munich International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 48.35388,
        'lonDeg' => 11.78611,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 12,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EGKK',
        'description' => 'London Gatwick Airport',
        'location_type' => 'AIRPORT',
        'lonDeg' => -0.19027,
        'latDeg' => 51.14805,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 5,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EPWA',
        'description' => 'Warsaw Chopin Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 52.16583,
        'lonDeg' => 20.96722,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 13,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EHAM',
        'description' => 'Amsterdam Airport Schiphol',
        'location_type' => 'AIRPORT',
        'latDeg' => 52.3086,
        'lonDeg' => 4.76389,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 3,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EHEH',
        'description' => 'Eindhoven Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 51.4501,
        'lonDeg' => 5.37453,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 19,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LEMD',
        'description' => 'Adolfo Suarez Madrid-Barajas Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 40.4719,
        'lonDeg' => -3.56264,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 7,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LEBL',
        'description' => 'Barcelona El Prat Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 41.2971,
        'lonDeg' => 2.07846,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 8,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LEMG',
        'description' => 'Malaga Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 36.6749,
        'lonDeg' => -4.49911,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 20,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EDDT',
        'description' => 'Berlin Tegel Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 52.5597,
        'lonDeg' => 13.2877,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EDDL',
        'description' => 'Dusseldorf Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 51.2895,
        'lonDeg' => 6.76678,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 21,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EPKT',
        'description' => 'Katowice International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 50.4743,
        'lonDeg' => 19.08,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 22,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EPPO',
        'description' => 'Poznań–Ławica Henryk Wieniawski Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 52.421,
        'lonDeg' => 16.8263,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 23,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LPPT',
        'description' => 'Lisbon Portela Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 38.7813,
        'lonDeg' => -9.13592,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 24,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LPPR',
        'description' => 'Francisco Sá Carneiro Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 41.2356,
        'lonDeg' => -8.67806,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 25,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LIRF',
        'description' => 'Rome–Fiumicino International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 41.8003,
        'lonDeg' => 12.2389,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 26,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LIML',
        'description' => 'Milan-Linate Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 45.4494,
        'lonDeg' => 9.2783,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 27,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LGAV',
        'description' => 'Athens International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 37.9364,
        'lonDeg' => 23.9445,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 28,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_LGIR',
        'description' => 'Heraklion International Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 35.3397,
        'lonDeg' => 25.1803,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 29,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EGCC',
        'description' => 'Manchester Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 53.3537,
        'lonDeg' => -2.27495,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 6,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EKCH',
        'description' => 'Copenhagen Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 55.6179,
        'lonDeg' => 12.656,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 29,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EKBI',
        'description' => 'Billund Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 55.7403,
        'lonDeg' => 9.15178,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 30,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EKYT',
        'description' => 'Aalborg Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 57.0928,
        'lonDeg' => 9.84924,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 31,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_ENGM',
        'description' => 'Oslo Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 60.1939,
        'lonDeg' => 11.1004,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 32,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_ESSB',
        'description' => 'Stockholm Bromma Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 59.3556,
        'lonDeg' => 17.9436,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 33,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@AIR_EFHK',
        'description' => 'Helsinki-Vantaa Airport',
        'location_type' => 'AIRPORT',
        'latDeg' => 60.3172,
        'lonDeg' => 24.9633,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 34,
        'created_at' => now(),
        'updated_at' => now(),
      ],


      // DISTRIBUTION_CENTERs
      [
        'id' => '@DC_BRUSSELS',
        'description' => 'EU Distribution Hub Brussels',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.9013,
        'lonDeg' => 4.48444,
        'isEntry' => false,
        'isExit' => false,
        'city_id' => 2,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_ANTWERP',
        'description' => 'Distribution Center Antwerp',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.18944,
        'lonDeg' => 4.46027,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_LOS_ANGELES',
        'description' => 'NA Distribution Hub Los Angeles',
        'location_type' => 'DISTRIBUTION_CENTER',
        'lonDeg' => -118.40805,
        'latDeg' => 33.94277,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 11,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_CHARLEROI',
        'description' => 'Charleroi Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.45916,
        'lonDeg' => 4.45388,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 14,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_MUNICH',
        'description' => 'Munich Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'lonDeg' => 11.78611,
        'latDeg' => 48.35388,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 12,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_LONDON',
        'description' => 'London Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.1480,
        'lonDeg' => -0.19027,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 5,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_WARSAW',
        'description' => 'Warsaw Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'lonDeg' => 20.96722,
        'latDeg' => 52.16583,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 13,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_TILBURG',
        'description' => 'Tilburg Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.565,
        'lonDeg' => 5.09111,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 15,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_BASTOGNE',
        'description' => 'Bastogne Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.00361,
        'lonDeg' => 5.72083,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 16,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_GHENT',
        'description' => 'Ghent Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.05,
        'lonDeg' => 3.71666,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 17,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_LILLE',
        'description' => 'Lille Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.63333,
        'lonDeg' => 3.06666,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 18,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_PARIS',
        'description' => 'Paris Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 48.85666,
        'lonDeg' => 2.35222,
        'isEntry' => true,
        'isExit' => false,
        'city_id' => 10,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_AMSTERDAM',
        'description' => 'Amsterdam Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 52.2930,
        'lonDeg' => 4.7692,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 3,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_EINDHOVEN',
        'description' => 'Eindhoven Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.4521,
        'lonDeg' => 5.3927,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 19,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_MADRID',
        'description' => 'Madrid Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 40.4561,
        'lonDeg' => -3.5626,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 7,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_BARCELONA',
        'description' => 'Barcelona Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 41.2987,
        'lonDeg' => 2.0634,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 8,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_MALAGA',
        'description' => 'Malaga Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 36.6623,
        'lonDeg' => -4.4905,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 20,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_BERLIN',
        'description' => 'Berlin Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 52.3764,
        'lonDeg' => 13.5409,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 9,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_DUSSELDORF',
        'description' => 'Dusseldorf Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 51.2847,
        'lonDeg' => 6.7763,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 21,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_KATOWICE',
        'description' => 'Katowice Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 50.4700,
        'lonDeg' => 19.0973,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 22,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_PONZAN',
        'description' => 'Poznań Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 52.4142,
        'lonDeg' => 16.8371,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 23,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_LISBOA',
        'description' => 'Lisboa Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 38.7816,
        'lonDeg' => -9.1256,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 24,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_PORTO',
        'description' => 'Porto Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 41.2382,
        'lonDeg' => -8.6865,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 25,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_ROME',
        'description' => 'Rome Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 41.8235,
        'lonDeg' => 12.2802,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 26,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_MILAN',
        'description' => 'Milan Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 45.4316,
        'lonDeg' => 9.2853,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 27,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_ATHENS',
        'description' => 'Athens Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 37.9212,
        'lonDeg' => 23.9342,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 28,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_HERAKLION',
        'description' => 'Heraklion Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 37.9212,
        'lonDeg' => 23.9342,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 28,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_MANCHESTER',
        'description' => 'Manchester Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 53.35793,
        'lonDeg' => -2.29143,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 6,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_COPENHAGEN',
        'description' => 'Copenhagen Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 55.6236,
        'lonDeg' => 12.6742,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 29,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_BILLUND',
        'description' => 'Billund Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 55.7369,
        'lonDeg' => 9.1374,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 30,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_AALBORG',
        'description' => 'Aalborg Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 57.0887,
        'lonDeg' => 9.9623,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 31,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_OSLO',
        'description' => 'Oslo Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 60.1926,
        'lonDeg' => 11.0870,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 32,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_STOCKHOLM',
        'description' => 'Stockholm Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 59.3569,
        'lonDeg' => 17.9500,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 33,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => '@DC_HELSINKI',
        'description' => 'Helsinki Distribution Center',
        'location_type' => 'DISTRIBUTION_CENTER',
        'latDeg' => 60.3194,
        'lonDeg' => 24.9083,
        'isEntry' => true,
        'isExit' => true,
        'city_id' => 34,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      //pickup_points
      [
        'id' => '@PIP_0001',
        'description' => 'Pick-up Point Antwerp 1',
        'location_type' => 'PICKUP_POINT',
        'latDeg' => 51.18944,
        'lonDeg' => 4.46027,
        'isEntry' => false,
        'isExit' => true,
        'city_id' => 1,
        'created_at' => now(),
        'updated_at' => now(),
      ],

      //TEST_NODE
      // [
      //   'id' => '@DISCONNECTED_TEST_NODE',
      //   'description' => 'Disconnected test node',
      //   'location_type' => 'DISTRIBUTION_CENTER',
      //   'latDeg' => 54.1536,
      //   'lonDeg' => 16.9913,
      //   'isEntry' => false,
      //   'isExit' => true,
      //   'city_id' => 1,
      //   'created_at' => now(),
      //   'updated_at' => now(),
      // ],
    ]);
  }
}

?>