name: New uninitialized task
description: Fill out this form to create a new task for the project.
labels: []
body:
  - type: input
    id: description
    attributes:
      label: Task description
      description: Explain what the task is about
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Note:** Upon creation, this task will be uninitialized.  
        You still have to assign labels in the detail page.