name: Create new uninitialized task
description: Create new uninitialized task in the project.
projects: ["GillesVanPellicom/1"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Task Description
      description: What is this task about?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Note:** Upon creation, this task will be uninitialized. You still have to assign labels in the detail page (next page) for it to show up correctly in the project.