name: New Issue
description: Fill out this form to create an issue.
title: "[New Issue] "
labels: ["pending"]
body:
  - type: markdown
    attributes:
      value: "Please fill out the details below."
  - type: dropdown
    id: Status
    attributes:
      label: "Project Status"
      options:
        - Pending
        - In Progress
        - Done
    validations:
      required: true